name = "nicovideo-ogp"
main = "nicovideo-ogp.js"
compatibility_date = "2025-07-09"
account_id = "09ea9996e2032911d59d2a89b10e0778"

[vars]
# 値は wrangler secret で設定することを推奨（下記はプレースホルダ）
MICROCMS_SERVICE_DOMAIN = ""
MICROCMS_API_KEY = ""

[dev]
port = 8787

[[rules]]
type = "ESModule"
globs = ["**/*.js"] 